[document]
PROPS({hyphenation, language="de-1996", margin_bottom=42.51968503937008, margin_left=34.01574803149607, margin_right=34.01574803149607, margin_top=42.51968503937008, paper="custom", paper_height=419.52755905511816, paper_width=297.6377952755906, title="Silbentrennung"})
T('Silbentrennung im Überblick')
NL({bold, font_size=16, hyphenate=False, role="h1", space_after=8})
T('Blocksatz: Die automatische Silbentrennung verbessert das Schriftbild erheblich, besonders bei schmalen Spalten und im Blocksatz. Ohne Trennung entstehen große Wortzwischenräume oder ein sehr unruhiger rechter Rand. Typische Beispiele sind lange Zusammensetzungen wie Donaudampfschifffahrtsgesellschaft, Bundesverfassungsgericht, Rechtsschutzversicherung und Textverarbeitungsprogramm.')
NL({alignment="justify"})
T('Linksbündig: Die automatische Silbentrennung verbessert das Schriftbild erheblich, besonders bei schmalen Spalten und im Blocksatz. Ohne Trennung entstehen große Wortzwischenräume oder ein sehr unruhiger rechter Rand. Typische Beispiele sind lange Zusammensetzungen wie Donaudampfschifffahrtsgesellschaft, Bundesverfassungsgericht, Rechtsschutzversicherung und Textverarbeitungsprogramm.')
NL({alignment="left"})
T('Rechtsbündig: Silbentrennung, Seitenumbruch, Fußnotenverwaltung und Inhaltsverzeichnisgenerierung.')
NL({alignment="right"})
T('Zentriert: Kopfzeilen, Fußzeilen und Abschnittsüberschriften werden getrennt.')
NL({alignment="center"})
T('Wörter mit Bindestrich: Der Hals-Nasen-Ohren-Arzt untersucht die Mund-Kiefer-Gesichtschirurgie und die Max-Planck-Gesellschaft. Ein frei stehender Strich - wie hier - und Daten wie 2026-10-06 werden nicht getrennt.')
NL({alignment="justify"})
T('Satzzeichen: Ist die Verfassungsbeschwerde (Bundesverfassungsgericht) zulässig? „Rechtsschutzversicherung“, sagte sie; Textverarbeitung!')
NL({alignment="justify"})
T('Ohne Trennung (Absatz mit Hyphenate aus): Die automatische Silbentrennung verbessert das Schriftbild erheblich, besonders bei schmalen Spalten und im Blocksatz. Ohne Trennung entstehen große Wortzwischenräume oder ein sehr unruhiger rechter Rand. Typische Beispiele sind lange Zusammensetzungen wie Donaudampfschifffahrtsgesellschaft, Bundesverfassungsgericht, Rechtsschutzversicherung und Textverarbeitungsprogramm.')
ENDMARK({alignment="justify", hyphenate=False})
